version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/autopp/go-mison

    steps:
      - checkout
      - run:
          name: install dependencies
          command: go mod download
      - run:
          name: run unit tests
          command: go test -v
